/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { BaseController } from './baseController';

export class CardlessCreditController extends BaseController {
  /**
   * @return Response from the API call
   */
  async createPayment(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/');
    return req.call(requestOptions);
  }
}
