/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  TokenizedCreatePaymentMethod,
  tokenizedCreatePaymentMethodSchema,
} from '../models/tokenizedCreatePaymentMethod';
import {
  TokenizedCreatePaymentMethodRequest,
  tokenizedCreatePaymentMethodRequestSchema,
} from '../models/tokenizedCreatePaymentMethodRequest';
import { BaseController } from './baseController';

export class CreatePaymentMethodStep3Controller extends BaseController {
  /**
   * Payment methods enable you to abstract sources of funds and use them for making direct debit
   * payments or recurring payments. Currently, only supports linked accounts.
   *
   * @param body
   * @return Response from the API call
   */
  async tokenizedCreatePaymentMethod(
    body: TokenizedCreatePaymentMethodRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TokenizedCreatePaymentMethod>> {
    const req = this.createRequest('POST', '/payment_methods');
    req.baseUrl('Server 1');
    const mapped = req.prepareArgs({
      body: [body, tokenizedCreatePaymentMethodRequestSchema],
    });
    req.json(mapped.body);
    return req.callAsJson(tokenizedCreatePaymentMethodSchema, requestOptions);
  }
}
