/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  CreateInvoiceRequest,
  createInvoiceRequestSchema,
} from '../models/createInvoiceRequest';
import {
  CreateInvoiceWFVARequest,
  createInvoiceWFVARequestSchema,
} from '../models/createInvoiceWFVARequest';
import { string } from '../schema';
import { BaseController } from './baseController';

export class InvoicesController extends BaseController {
  /**
   * [[API Reference] - Create Invoice](https://xendit.github.io/apireference/#create-invoices)
   *
   * [[Xendit Docs] - Invoices](https://docs.xendit.co/xeninvoice/)
   *
   * @param contentType
   * @param body
   * @return Response from the API call
   */
  async createInvoice(
    contentType: string,
    body: CreateInvoiceRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/v2/invoices');
    req.baseUrl('Server 1');
    const mapped = req.prepareArgs({
      contentType: [contentType, string()],
      body: [body, createInvoiceRequestSchema],
    });
    req.header('Content-Type', mapped.contentType);
    req.json(mapped.body);
    return req.call(requestOptions);
  }

  /**
   * [[API Reference] - Create Invoice](https://xendit.github.io/apireference/#create-invoices)
   *
   * [[Xendit Docs] - Invoices](https://docs.xendit.co/xeninvoice/)
   *
   * @param contentType
   * @param body
   * @return Response from the API call
   */
  async createInvoiceWFVA(
    contentType: string,
    body: CreateInvoiceWFVARequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/v2/invoices');
    req.baseUrl('Server 1');
    const mapped = req.prepareArgs({
      contentType: [contentType, string()],
      body: [body, createInvoiceWFVARequestSchema],
    });
    req.header('Content-Type', mapped.contentType);
    req.json(mapped.body);
    return req.call(requestOptions);
  }

  /**
   * [[API Reference] - Get Invoice](https://xendit.github.io/apireference/#get-an-invoice)
   *
   * [[Xendit Docs] - Invoices](https://docs.xendit.co/xeninvoice/)
   *
   * @return Response from the API call
   */
  async getInvoice(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest(
      'GET',
      '/v2/invoices/5bdaa3d70b993c3b0ee8a162'
    );
    req.baseUrl('Server 1');
    return req.call(requestOptions);
  }
}
