/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { BaseController } from './baseController';

export class MiscController extends BaseController {
  /**
   * @return Response from the API call
   */
  async getBalance(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/balance');
    req.baseUrl('Server 1');
    return req.call(requestOptions);
  }
}
