/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { Account, accountSchema } from './account';

export interface AccountLinkingCallbackNotificationRequest {
  event: string;
  timestamp: string;
  id: string;
  channelCode: string;
  type: string;
  accounts: Account[];
}

export const accountLinkingCallbackNotificationRequestSchema: Schema<AccountLinkingCallbackNotificationRequest> = object(
  {
    event: ['event', string()],
    timestamp: ['timestamp', string()],
    id: ['id', string()],
    channelCode: ['channel_code', string()],
    type: ['type', string()],
    accounts: ['accounts', array(lazy(() => accountSchema))],
  }
);
