/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, Schema, string } from '../schema';

export interface Account {
  id: string;
  accountDetails: string | null;
  accountType: string;
  balance: number;
  currency: string;
  description: string | null;
  name: string | null;
  pointBalance: string | null;
}

export const accountSchema: Schema<Account> = object({
  id: ['id', string()],
  accountDetails: ['account_details', nullable(string())],
  accountType: ['account_type', string()],
  balance: ['balance', number()],
  currency: ['currency', string()],
  description: ['description', nullable(string())],
  name: ['name', nullable(string())],
  pointBalance: ['point_balance', nullable(string())],
});
