/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, Schema, string } from '../schema';

export interface Actions {
  desktopWebCheckoutUrl: string;
  mobileWebCheckoutUrl: string;
  mobileDeeplinkCheckoutUrl: string | null;
  qrCheckoutString: string | null;
}

export const actionsSchema: Schema<Actions> = object({
  desktopWebCheckoutUrl: ['desktop_web_checkout_url', string()],
  mobileWebCheckoutUrl: ['mobile_web_checkout_url', string()],
  mobileDeeplinkCheckoutUrl: [
    'mobile_deeplink_checkout_url',
    nullable(string()),
  ],
  qrCheckoutString: ['qr_checkout_string', nullable(string())],
});
