/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, Schema, string } from '../schema';

export interface AuthorizeHoldAmountRequest {
  tokenId: string;
  externalId: string;
  amount: number;
  cardCvn: string;
  capture: boolean;
}

export const authorizeHoldAmountRequestSchema: Schema<AuthorizeHoldAmountRequest> = object(
  {
    tokenId: ['token_id', string()],
    externalId: ['external_id', string()],
    amount: ['amount', number()],
    cardCvn: ['card_cvn', string()],
    capture: ['capture', boolean()],
  }
);
