/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Properties7, properties7Schema } from './properties7';

export interface BindingInitiateAccountAuthorizationRequest {
  customerId: string;
  channelCode: string;
  properties: Properties7;
}

export const bindingInitiateAccountAuthorizationRequestSchema: Schema<BindingInitiateAccountAuthorizationRequest> = object(
  {
    customerId: ['customer_id', string()],
    channelCode: ['channel_code', string()],
    properties: ['properties', lazy(() => properties7Schema)],
  }
);
