/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Properties4, properties4Schema } from './properties4';

export interface BindingCreatePaymentMethodRequest {
  customerId: string;
  type: string;
  properties: Properties4;
}

export const bindingCreatePaymentMethodRequestSchema: Schema<BindingCreatePaymentMethodRequest> = object(
  {
    customerId: ['customer_id', string()],
    type: ['type', string()],
    properties: ['properties', lazy(() => properties4Schema)],
  }
);
