/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface BusinessProfile {
  businessName: string;
}

export const businessProfileSchema: Schema<BusinessProfile> = object({
  businessName: ['business_name', string()],
});
