/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema';

export interface CaptureAuthRequest {
  amount: number;
}

export const captureAuthRequestSchema: Schema<CaptureAuthRequest> = object({
  amount: ['amount', number()],
});
