/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ChannelProperties2 {
  successRedirectUrl: string;
  failureRedirectUrl: string;
  redeemPoints: string;
}

export const channelProperties2Schema: Schema<ChannelProperties2> = object({
  successRedirectUrl: ['success_redirect_url', string()],
  failureRedirectUrl: ['failure_redirect_url', string()],
  redeemPoints: ['redeem_points', string()],
});
