/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ChannelProperties4 {
  successRedirectUrl: string;
}

export const channelProperties4Schema: Schema<ChannelProperties4> = object({
  successRedirectUrl: ['success_redirect_url', string()],
});
