/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ChannelProperties12 {
  successRedirectUrl: string;
  failureRedirectUrl: string;
}

export const channelProperties12Schema: Schema<ChannelProperties12> = object({
  successRedirectUrl: ['success_redirect_url', string()],
  failureRedirectUrl: ['failure_redirect_url', string()],
});
