/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ChannelProperties6 {
  successRedirectUrl: string;
  redeemPoints: string;
}

export const channelProperties6Schema: Schema<ChannelProperties6> = object({
  successRedirectUrl: ['success_redirect_url', string()],
  redeemPoints: ['redeem_points', string()],
});
