/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ChannelProperties {
  mobileNumber: string;
}

export const channelPropertiesSchema: Schema<ChannelProperties> = object({
  mobileNumber: ['mobile_number', string()],
});
