/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ChannelProperties14 {
  successRedirectUrl: string;
  failureRedirectUrl: string;
  cancelRedirectUrl: string;
}

export const channelProperties14Schema: Schema<ChannelProperties14> = object({
  successRedirectUrl: ['success_redirect_url', string()],
  failureRedirectUrl: ['failure_redirect_url', string()],
  cancelRedirectUrl: ['cancel_redirect_url', string()],
});
