/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface ChargeAuthCaptureRequest {
  tokenId: string;
  externalId: string;
  amount: number;
  cardCvn: string;
}

export const chargeAuthCaptureRequestSchema: Schema<ChargeAuthCaptureRequest> = object(
  {
    tokenId: ['token_id', string()],
    externalId: ['external_id', string()],
    amount: ['amount', number()],
    cardCvn: ['card_cvn', string()],
  }
);
