/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, Schema, string } from '../schema';
import { Metadata2, metadata2Schema } from './metadata2';

export interface CreateGrabpayTokenizedEWalletChargeRequest {
  referenceId: string;
  currency: string;
  amount: number;
  checkoutMethod: string;
  paymentMethodId: string;
  metadata: Metadata2;
}

export const createGrabpayTokenizedEWalletChargeRequestSchema: Schema<CreateGrabpayTokenizedEWalletChargeRequest> = object(
  {
    referenceId: ['reference_id', string()],
    currency: ['currency', string()],
    amount: ['amount', number()],
    checkoutMethod: ['checkout_method', string()],
    paymentMethodId: ['payment_method_id', string()],
    metadata: ['metadata', lazy(() => metadata2Schema)],
  }
);
