/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, Schema, string } from '../schema';
import {
  ChannelProperties,
  channelPropertiesSchema,
} from './channelProperties';
import { Metadata, metadataSchema } from './metadata';

export interface CreateOVOEWalletChargeRequest {
  referenceId: string;
  currency: string;
  amount: number;
  checkoutMethod: string;
  channelCode: string;
  channelProperties: ChannelProperties;
  metadata: Metadata;
}

export const createOVOEWalletChargeRequestSchema: Schema<CreateOVOEWalletChargeRequest> = object(
  {
    referenceId: ['reference_id', string()],
    currency: ['currency', string()],
    amount: ['amount', number()],
    checkoutMethod: ['checkout_method', string()],
    channelCode: ['channel_code', string()],
    channelProperties: [
      'channel_properties',
      lazy(() => channelPropertiesSchema),
    ],
    metadata: ['metadata', lazy(() => metadataSchema)],
  }
);
