/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { BusinessProfile, businessProfileSchema } from './businessProfile';

export interface CreateAccountRequest {
  accountEmail: string;
  type: string;
  businessProfile: BusinessProfile;
}

export const createAccountRequestSchema: Schema<CreateAccountRequest> = object({
  accountEmail: ['account_email', string()],
  type: ['type', string()],
  businessProfile: ['business_profile', lazy(() => businessProfileSchema)],
});
