/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface CreateQRCodeRequest {
  externalId: string;
  type: string;
  callbackUrl: string;
  amount: number;
}

export const createQRCodeRequestSchema: Schema<CreateQRCodeRequest> = object({
  externalId: ['external_id', string()],
  type: ['type', string()],
  callbackUrl: ['callback_url', string()],
  amount: ['amount', number()],
});
