/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface CreateInvoiceWFVARequest {
  externalId: string;
  amount: number;
  payerEmail: string;
  description: string;
  callbackVirtualAccountId: string;
}

export const createInvoiceWFVARequestSchema: Schema<CreateInvoiceWFVARequest> = object(
  {
    externalId: ['external_id', string()],
    amount: ['amount', number()],
    payerEmail: ['payer_email', string()],
    description: ['description', string()],
    callbackVirtualAccountId: ['callback_virtual_account_id', string()],
  }
);
