/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { Route, routeSchema } from './route';

export interface CreateFeeRuleRequest {
  name: string;
  description: string;
  routes: Route[];
}

export const createFeeRuleRequestSchema: Schema<CreateFeeRuleRequest> = object({
  name: ['name', string()],
  description: ['description', string()],
  routes: ['routes', array(lazy(() => routeSchema))],
});
