/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface CreateFVARequest {
  externalId: string;
  bankCode: string;
  name: string;
}

export const createFVARequestSchema: Schema<CreateFVARequest> = object({
  externalId: ['external_id', string()],
  bankCode: ['bank_code', string()],
  name: ['name', string()],
});
