/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, Schema, string } from '../schema';
import {
  ChannelProperties14,
  channelProperties14Schema,
} from './channelProperties14';
import { Metadata12, metadata12Schema } from './metadata12';

export interface CreatePaymayaEWalletChargeRequest {
  referenceId: string;
  currency: string;
  amount: number;
  checkoutMethod: string;
  channelCode: string;
  channelProperties: ChannelProperties14;
  metadata: Metadata12;
}

export const createPaymayaEWalletChargeRequestSchema: Schema<CreatePaymayaEWalletChargeRequest> = object(
  {
    referenceId: ['reference_id', string()],
    currency: ['currency', string()],
    amount: ['amount', number()],
    checkoutMethod: ['checkout_method', string()],
    channelCode: ['channel_code', string()],
    channelProperties: [
      'channel_properties',
      lazy(() => channelProperties14Schema),
    ],
    metadata: ['metadata', lazy(() => metadata12Schema)],
  }
);
