/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, Schema, string } from '../schema';
import {
  ChannelProperties12,
  channelProperties12Schema,
} from './channelProperties12';
import { Metadata2, metadata2Schema } from './metadata2';

export interface CreateGrabpayEWalletChargeRequest {
  referenceId: string;
  currency: string;
  amount: number;
  checkoutMethod: string;
  channelCode: string;
  channelProperties: ChannelProperties12;
  metadata: Metadata2;
}

export const createGrabpayEWalletChargeRequestSchema: Schema<CreateGrabpayEWalletChargeRequest> = object(
  {
    referenceId: ['reference_id', string()],
    currency: ['currency', string()],
    amount: ['amount', number()],
    checkoutMethod: ['checkout_method', string()],
    channelCode: ['channel_code', string()],
    channelProperties: [
      'channel_properties',
      lazy(() => channelProperties12Schema),
    ],
    metadata: ['metadata', lazy(() => metadata2Schema)],
  }
);
