/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface CreateFPCIndomaretRequest {
  externalId: string;
  retailOutletName: string;
  name: string;
  expectedAmount: number;
}

export const createFPCIndomaretRequestSchema: Schema<CreateFPCIndomaretRequest> = object(
  {
    externalId: ['external_id', string()],
    retailOutletName: ['retail_outlet_name', string()],
    name: ['name', string()],
    expectedAmount: ['expected_amount', number()],
  }
);
