/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface CreateTransferRequest {
  reference: string;
  amount: number;
  sourceUserId: string;
  destinationUserId: string;
}

export const createTransferRequestSchema: Schema<CreateTransferRequest> = object(
  {
    reference: ['reference', string()],
    amount: ['amount', number()],
    sourceUserId: ['source_user_id', string()],
    destinationUserId: ['destination_user_id', string()],
  }
);
