/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { Disbursement, disbursementSchema } from './disbursement';

export interface CreateBatchDisbursementRequest {
  reference: string;
  disbursements: Disbursement[];
}

export const createBatchDisbursementRequestSchema: Schema<CreateBatchDisbursementRequest> = object(
  {
    reference: ['reference', string()],
    disbursements: ['disbursements', array(lazy(() => disbursementSchema))],
  }
);
