/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

export interface Disbursement {
  amount: number;
  bankCode: string;
  bankAccountName: string;
  bankAccountNumber: string;
  description: string;
  externalId: string;
  emailTo?: string[];
  emailCc?: string[];
  emailBcc?: string[];
}

export const disbursementSchema: Schema<Disbursement> = object({
  amount: ['amount', number()],
  bankCode: ['bank_code', string()],
  bankAccountName: ['bank_account_name', string()],
  bankAccountNumber: ['bank_account_number', string()],
  description: ['description', string()],
  externalId: ['external_id', string()],
  emailTo: ['email_to', optional(array(string()))],
  emailCc: ['email_cc', optional(array(string()))],
  emailBcc: ['email_bcc', optional(array(string()))],
});
