/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, Schema, string } from '../schema';

export interface EXAMPLECreateRecurringPaymentForSubAccountRequestRequest {
  externalId: string;
  payerEmail: string;
  description: string;
  amount: number;
  interval: string;
  intervalCount: string;
  shouldSendEmail: boolean;
}

export const eXAMPLECreateRecurringPaymentForSubAccountRequestRequestSchema: Schema<EXAMPLECreateRecurringPaymentForSubAccountRequestRequest> = object(
  {
    externalId: ['external_id', string()],
    payerEmail: ['payer_email', string()],
    description: ['description', string()],
    amount: ['amount', number()],
    interval: ['interval', string()],
    intervalCount: ['interval_count', string()],
    shouldSendEmail: ['should_send_email', boolean()],
  }
);
