/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface EXAMPLECreateDisbursementForSubAccountRequestRequest {
  externalId: string;
  bankCode: string;
  accountHolderName: string;
  accountNumber: string;
  description: string;
}

export const eXAMPLECreateDisbursementForSubAccountRequestRequestSchema: Schema<EXAMPLECreateDisbursementForSubAccountRequestRequest> = object(
  {
    externalId: ['external_id', string()],
    bankCode: ['bank_code', string()],
    accountHolderName: ['account_holder_name', string()],
    accountNumber: ['account_number', string()],
    description: ['description', string()],
  }
);
