/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Filter, filterSchema } from './filter';

export interface GenerateReportRequest {
  type: string;
  filter: Filter;
  format: string;
  currency: string;
}

export const generateReportRequestSchema: Schema<GenerateReportRequest> = object(
  {
    type: ['type', string()],
    filter: ['filter', lazy(() => filterSchema)],
    format: ['format', string()],
    currency: ['currency', string()],
  }
);
