/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Metadata22 {
  branchCode: string;
}

export const metadata22Schema: Schema<Metadata22> = object({
  branchCode: ['branch_code', string()],
});
