/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Metadata12 {
  branchCity: string;
}

export const metadata12Schema: Schema<Metadata12> = object({
  branchCity: ['branch_city', string()],
});
