/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Metadata2 {
  branchCode: string;
  branchCity: string;
}

export const metadata2Schema: Schema<Metadata2> = object({
  branchCode: ['branch_code', string()],
  branchCity: ['branch_city', string()],
});
