/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface OVOTokenizedCreateCustomerRequest {
  referenceId: string;
  mobileNumber: string;
  givenNames: string;
}

export const oVOTokenizedCreateCustomerRequestSchema: Schema<OVOTokenizedCreateCustomerRequest> = object(
  {
    referenceId: ['reference_id', string()],
    mobileNumber: ['mobile_number', string()],
    givenNames: ['given_names', string()],
  }
);
