/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, Schema, string } from '../schema';

export interface OVOTokenizedCreateCustomer {
  id: string;
  referenceId: string;
  givenNames: string;
  email: string | null;
  mobileNumber: string;
  description: string | null;
  middleName: string | null;
  surname: string | null;
  phoneNumber: string | null;
  nationality: string | null;
  dateOfBirth: string | null;
  metadata: string | null;
  employment: string | null;
  addresses: string | null;
  sourceOfWealth: string | null;
}

export const oVOTokenizedCreateCustomerSchema: Schema<OVOTokenizedCreateCustomer> = object(
  {
    id: ['id', string()],
    referenceId: ['reference_id', string()],
    givenNames: ['given_names', string()],
    email: ['email', nullable(string())],
    mobileNumber: ['mobile_number', string()],
    description: ['description', nullable(string())],
    middleName: ['middle_name', nullable(string())],
    surname: ['surname', nullable(string())],
    phoneNumber: ['phone_number', nullable(string())],
    nationality: ['nationality', nullable(string())],
    dateOfBirth: ['date_of_birth', nullable(string())],
    metadata: ['metadata', nullable(string())],
    employment: ['employment', nullable(string())],
    addresses: ['addresses', nullable(string())],
    sourceOfWealth: ['source_of_wealth', nullable(string())],
  }
);
