/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, Schema, string } from '../schema';

export interface PaymentOneTimePaymentWOTPRequest {
  referenceId: string;
  paymentMethodId: string;
  currency: string;
  amount: number;
  enableOtp: boolean;
  callbackUrl: string;
}

export const paymentOneTimePaymentWOTPRequestSchema: Schema<PaymentOneTimePaymentWOTPRequest> = object(
  {
    referenceId: ['reference_id', string()],
    paymentMethodId: ['payment_method_id', string()],
    currency: ['currency', string()],
    amount: ['amount', number()],
    enableOtp: ['enable_otp', boolean()],
    callbackUrl: ['callback_url', string()],
  }
);
