/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Properties1, properties1Schema } from './properties1';

export interface PaymayaTokenizedAccountLinkingRequest {
  customerId: string;
  channelCode: string;
  properties: Properties1;
}

export const paymayaTokenizedAccountLinkingRequestSchema: Schema<PaymayaTokenizedAccountLinkingRequest> = object(
  {
    customerId: ['customer_id', string()],
    channelCode: ['channel_code', string()],
    properties: ['properties', lazy(() => properties1Schema)],
  }
);
