/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface PaymentValidateOTPOneTimePaymentWOTPRequest {
  otpCode: string;
}

export const paymentValidateOTPOneTimePaymentWOTPRequestSchema: Schema<PaymentValidateOTPOneTimePaymentWOTPRequest> = object(
  { otpCode: ['otp_code', string()] }
);
