/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface PaymentRecurringPaymentsRequest {
  externalId: string;
  payerEmail: string;
  description: string;
  paymentMethodId: string;
  amount: number;
  interval: string;
  intervalCount: number;
}

export const paymentRecurringPaymentsRequestSchema: Schema<PaymentRecurringPaymentsRequest> = object(
  {
    externalId: ['external_id', string()],
    payerEmail: ['payer_email', string()],
    description: ['description', string()],
    paymentMethodId: ['payment_method_id', string()],
    amount: ['amount', number()],
    interval: ['interval', string()],
    intervalCount: ['interval_count', number()],
  }
);
