/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface PROCESSORERRORREQUEST {
  tokenId: string;
  externalId: string;
  amount: number;
}

export const pROCESSORERRORREQUESTSchema: Schema<PROCESSORERRORREQUEST> = object(
  {
    tokenId: ['token_id', string()],
    externalId: ['external_id', string()],
    amount: ['amount', number()],
  }
);
