/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Properties7 {
  accountMobileNumber: string;
  cardLastFour: string;
  cardExpiry: string;
  accountEmail: string;
}

export const properties7Schema: Schema<Properties7> = object({
  accountMobileNumber: ['account_mobile_number', string()],
  cardLastFour: ['card_last_four', string()],
  cardExpiry: ['card_expiry', string()],
  accountEmail: ['account_email', string()],
});
