/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Properties1 {
  successRedirectUrl: string;
  failureRedirectUrl: string;
  cancelRedirectUrl: string;
  callbackUrl: string;
}

export const properties1Schema: Schema<Properties1> = object({
  successRedirectUrl: ['success_redirect_url', string()],
  failureRedirectUrl: ['failure_redirect_url', string()],
  cancelRedirectUrl: ['cancel_redirect_url', string()],
  callbackUrl: ['callback_url', string()],
});
