/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Properties8 {
  cardLastFour: string;
  cardExpiry: string;
  currency: string;
  description: string;
}

export const properties8Schema: Schema<Properties8> = object({
  cardLastFour: ['card_last_four', string()],
  cardExpiry: ['card_expiry', string()],
  currency: ['currency', string()],
  description: ['description', string()],
});
