/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Properties4 {
  id: string;
}

export const properties4Schema: Schema<Properties4> = object({
  id: ['id', string()],
});
