/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, Schema, string } from '../schema';

export interface Properties6 {
  accountDetails: string;
  accountType: string;
  balance: string | null;
  currency: string;
  description: string | null;
  name: string;
  pointBalance: string | null;
}

export const properties6Schema: Schema<Properties6> = object({
  accountDetails: ['account_details', string()],
  accountType: ['account_type', string()],
  balance: ['balance', nullable(string())],
  currency: ['currency', string()],
  description: ['description', nullable(string())],
  name: ['name', string()],
  pointBalance: ['point_balance', nullable(string())],
});
