/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface RefundChargeByExternalIDRequest {
  amount: number;
  externalId: string;
}

export const refundChargeByExternalIDRequestSchema: Schema<RefundChargeByExternalIDRequest> = object(
  { amount: ['amount', number()], externalId: ['external_id', string()] }
);
