/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ReverseAuthRequest {
  externalId: string;
}

export const reverseAuthRequestSchema: Schema<ReverseAuthRequest> = object({
  externalId: ['external_id', string()],
});
