/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface Route {
  unit: string;
  amount: number;
  currency: string;
}

export const routeSchema: Schema<Route> = object({
  unit: ['unit', string()],
  amount: ['amount', number()],
  currency: ['currency', string()],
});
