/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Data, dataSchema } from './data';

export interface SamplePaymentNotificationFromXenditRequest {
  event: string;
  businessId: string;
  created: string;
  data: Data;
}

export const samplePaymentNotificationFromXenditRequestSchema: Schema<SamplePaymentNotificationFromXenditRequest> = object(
  {
    event: ['event', string()],
    businessId: ['business_id', string()],
    created: ['created', string()],
    data: ['data', lazy(() => dataSchema)],
  }
);
