/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ShopeepayTokenizedCreateCustomerCopyRequest {
  referenceId: string;
  email: string;
  givenNames: string;
}

export const shopeepayTokenizedCreateCustomerCopyRequestSchema: Schema<ShopeepayTokenizedCreateCustomerCopyRequest> = object(
  {
    referenceId: ['reference_id', string()],
    email: ['email', string()],
    givenNames: ['given_names', string()],
  }
);
