/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Properties, propertiesSchema } from './properties';

export interface ShopeepayTokenizedAccountLinkingRequest {
  customerId: string;
  channelCode: string;
  properties: Properties;
}

export const shopeepayTokenizedAccountLinkingRequestSchema: Schema<ShopeepayTokenizedAccountLinkingRequest> = object(
  {
    customerId: ['customer_id', string()],
    channelCode: ['channel_code', string()],
    properties: ['properties', lazy(() => propertiesSchema)],
  }
);
