/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface SuccessfullyInitiatedAnAuthorizationRequest {
  id: string;
  customerId: string;
  channelCode: string;
  status: string;
  type: string;
  authorizerUrl: string;
}

export const successfullyInitiatedAnAuthorizationRequestSchema: Schema<SuccessfullyInitiatedAnAuthorizationRequest> = object(
  {
    id: ['id', string()],
    customerId: ['customer_id', string()],
    channelCode: ['channel_code', string()],
    status: ['status', string()],
    type: ['type', string()],
    authorizerUrl: ['authorizer_url', string()],
  }
);
