/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Properties8, properties8Schema } from './properties8';

export interface SuccessfullyRetrievedAccessibleAccountsForALinkedAccountTokenCopy {
  id: string;
  channelCode: string;
  type: string;
  properties: Properties8;
}

export const successfullyRetrievedAccessibleAccountsForALinkedAccountTokenCopySchema: Schema<SuccessfullyRetrievedAccessibleAccountsForALinkedAccountTokenCopy> = object(
  {
    id: ['id', string()],
    channelCode: ['channel_code', string()],
    type: ['type', string()],
    properties: ['properties', lazy(() => properties8Schema)],
  }
);
