/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema, string } from '../schema';

export interface SuccessfullyDeletedALinkedAccountToken {
  id: string;
  isDeleted: boolean;
}

export const successfullyDeletedALinkedAccountTokenSchema: Schema<SuccessfullyDeletedALinkedAccountToken> = object(
  { id: ['id', string()], isDeleted: ['is_deleted', boolean()] }
);
