/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface Success {
  updated: string;
  created: string;
  creditCardChargeId: string;
  userId: string;
  amount: number;
  externalId: string;
  status: string;
  id: string;
  feeRefundAmount: number;
}

export const successSchema: Schema<Success> = object({
  updated: ['updated', string()],
  created: ['created', string()],
  creditCardChargeId: ['credit_card_charge_id', string()],
  userId: ['user_id', string()],
  amount: ['amount', number()],
  externalId: ['external_id', string()],
  status: ['status', string()],
  id: ['id', string()],
  feeRefundAmount: ['fee_refund_amount', number()],
});
