/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface Success1 {
  created: string;
  businessId: string;
  authorizedAmount: number;
  externalId: string;
  merchantId: string;
  merchantReferenceCode: string;
  maskedCardNumber: string;
  chargeType: string;
  cardBrand: string;
  cardType: string;
  bankReconciliationId: string;
  status: string;
  eci: string;
  captureAmount: number;
  id: string;
}

export const success1Schema: Schema<Success1> = object({
  created: ['created', string()],
  businessId: ['business_id', string()],
  authorizedAmount: ['authorized_amount', number()],
  externalId: ['external_id', string()],
  merchantId: ['merchant_id', string()],
  merchantReferenceCode: ['merchant_reference_code', string()],
  maskedCardNumber: ['masked_card_number', string()],
  chargeType: ['charge_type', string()],
  cardBrand: ['card_brand', string()],
  cardType: ['card_type', string()],
  bankReconciliationId: ['bank_reconciliation_id', string()],
  status: ['status', string()],
  eci: ['eci', string()],
  captureAmount: ['capture_amount', number()],
  id: ['id', string()],
});
