/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface TESTPaymentInvoiceVARequest {
  bankCode: string;
  bankAccountNumber: string;
  transferAmount: number;
}

export const tESTPaymentInvoiceVARequestSchema: Schema<TESTPaymentInvoiceVARequest> = object(
  {
    bankCode: ['bank_code', string()],
    bankAccountNumber: ['bank_account_number', string()],
    transferAmount: ['transfer_amount', number()],
  }
);
