/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema';

export interface TESTPayFVARequest {
  amount: number;
}

export const tESTPayFVARequestSchema: Schema<TESTPayFVARequest> = object({
  amount: ['amount', number()],
});
