/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface TESTDisbursementFailRejectedBecauseFatalErrorRequest {
  externalId: string;
  amount: number;
  bankCode: string;
  accountHolderName: string;
  accountNumber: string;
  description: string;
}

export const tESTDisbursementFailRejectedBecauseFatalErrorRequestSchema: Schema<TESTDisbursementFailRejectedBecauseFatalErrorRequest> = object(
  {
    externalId: ['external_id', string()],
    amount: ['amount', number()],
    bankCode: ['bank_code', string()],
    accountHolderName: ['account_holder_name', string()],
    accountNumber: ['account_number', string()],
    description: ['description', string()],
  }
);
