/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Properties6, properties6Schema } from './properties6';

export interface TokenizedGetAccountBalance {
  channelCode: string;
  id: string;
  type: string;
  properties: Properties6;
}

export const tokenizedGetAccountBalanceSchema: Schema<TokenizedGetAccountBalance> = object(
  {
    channelCode: ['channel_code', string()],
    id: ['id', string()],
    type: ['type', string()],
    properties: ['properties', lazy(() => properties6Schema)],
  }
);
