/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string, unknown } from '../schema';
import { Properties4, properties4Schema } from './properties4';

export interface TokenizedCreatePaymentMethod {
  customerId: string;
  type: string;
  properties: Properties4;
  status: string;
  metadata?: unknown;
  id: string;
  created: string;
  updated: string;
}

export const tokenizedCreatePaymentMethodSchema: Schema<TokenizedCreatePaymentMethod> = object(
  {
    customerId: ['customer_id', string()],
    type: ['type', string()],
    properties: ['properties', lazy(() => properties4Schema)],
    status: ['status', string()],
    metadata: ['metadata', unknown()],
    id: ['id', string()],
    created: ['created', string()],
    updated: ['updated', string()],
  }
);
