/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface UpdatePaymentCodeRequest {
  customerName: string;
  amount: number;
  currency: string;
}

export const updatePaymentCodeRequestSchema: Schema<UpdatePaymentCodeRequest> = object(
  {
    customerName: ['customer_name', string()],
    amount: ['amount', number()],
    currency: ['currency', string()],
  }
);
