/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface UpdateVirtualAccountRequest {
  expectedAmount: string;
}

export const updateVirtualAccountRequestSchema: Schema<UpdateVirtualAccountRequest> = object(
  { expectedAmount: ['expected_amount', string()] }
);
