/**
 * API-XenditLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { PublicProfile, publicProfileSchema } from './publicProfile';

export interface V2UpdateAccountRequest {
  email: string;
  publicProfile: PublicProfile;
}

export const v2UpdateAccountRequestSchema: Schema<V2UpdateAccountRequest> = object(
  {
    email: ['email', string()],
    publicProfile: ['public_profile', lazy(() => publicProfileSchema)],
  }
);
